### ISSUE TITLE
Does the author of slides have to be the same as the course authors?

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#14]
It seems that the HTML display mode of slides includes a header and front slide that lists the title and author. The author is apparently taken from the config.yml course-level author. I anticipate using coursebuilder for a module where there are multiple people teaching the module, but different people are responsible for different sections, and it would be good if we could put the relevant author on a set of slides rather than everybody.

I tried setting `\author{Peter Rowlett}` in my beamer preamble and tried adding an `author` under the relevant `content` item in the yml, but neither of these resulted in a change to the slides author. 

```
      content:
        - type: slides
          title: Slides title
          source: slides/slides.tex
          author: Peter Rowlett
```

Is something like this possible? It would make more sense if the HTML slides display mode respected the `\author{}` property from the beamer document.
