### ISSUE TITLE
Success reporting

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#33]
I have my course set up to produce the themes used in the sample course:
```
themes: 
  - title: Default
    source: default
    path: default
  - title: Accessible
    source: accessible
    path: accessible
```
I noticed that when I run `makecourse` (not verbose mode) the output ends "`All done! Output written to build/accessible`", but I always go to `build/default`. I guess it is saying this because the Accessible theme is created second, but it seems that if it is creating multiple themes it should perhaps report the default one (assuming this to be the one called Default or the first, as this is the one that will be first in the drop-down list on the web page), or just say "`All done! Output written to build/*`" or something.
