### ISSUE TITLE
Detect generated filename collisions and work around them

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#51]
I have an entry in my config.yml that is something like this:

```
    - type: part
      title: The title of a part
      content:
        - type: part
          title: Quite a long title here for the sub-part within the part
          content:
            - type: slides
              title: Actually a pretty long title for a set of slides now I come to think of it
              source: slides.tex
```

Ubuntu likes this fine, but when @Alex-Corner tried to copy the course (via GitHub) onto his Windows machine he got an error like this:

```
error: unable to create file build/default/the_title_of_a_part/Quite_a_long_title_here_for_the_sub-part_within_the_part/actually_a_pretty_long_title_for_a_set_of_slides_now_I_come_to_think_of_it/actually_a_pretty_long_title_for_a_set_of_slides_now_I_come_to_think_of_it.pdf: Filename too long
```

The file and folder names come from the titles of parts and other content in `config.yml`. To solve the immediate problem, I have used a shorter title, and Alex has pulled this version of the course successfully. 

To be clear: Alex isn't running `makecourse` on Windows, but on an Ubuntu virtual machine because he hasn't been able to get it running on Windows. But presumably if he were running `makecourse` on Windows and tried to build a course with a long filename it would hit issues. 

Also, presumably if the web server I'm using is running Windows, it would have a similar problem copying the build across. 

So: could you truncate the filenames somewhere reasonable to prevent this kind of error? 10 characters from the title is probably enough to distinguish most files? But I guess you'd have to check and add a number to the end if truncating a file causes it to have the same name as an existing file in that build folder.
